- name: Check whether docker is already installed
  shell: which docker
  ignore_errors: yes
  register: docker_installed

- block:
  - name: download install script
    get_url:
      url: https://get.docker.com
      dest: /tmp/install_docker.sh
      mode: 0775

  - name: run install script
    command: /tmp/install_docker.sh

  - name: Add user to docker group
    command: "usermod -a -G docker {{ create_user }}"

  - name: Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose

  when: docker_installed.stdout == ""
