- name: Check whether gh is already installed
  shell: which gh
  ignore_errors: yes
  register: gh_installed

- block:
  - name: Add gh repo apt key
    shell:
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
  - name: Add gh apt repository
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages focal main"
      state: present

  - name: Update apt
    apt:
      update_cache: yes

  - name: Install gh
    apt:
      name: gh
      state: latest

  - set_fact: token="{{ lookup('env','GITHUB_TOKEN') }}"

  when: gh_installed.stdout == ""
