# https://github.com/do-community/ansible-playbooks/blob/master/setup_ubuntu1804/playbook.yml
- name: Install Prerequisites
  apt:
    name: aptitude
    update_cache: yes
    state: latest
    force_apt_get: yes

- name: Update apt
  apt:
    update_cache: yes

- name: Install required system packages
  apt:
    name: "{{ sys_packages }}"
    state: latest

- name: Check whether nvim is already installed
  shell: which nvim
  ignore_errors: yes
  register: nvim_installed

- block:
  - name: Add neovim apt repository
    apt_repository:
      repo: ppa:neovim-ppa/stable
      state: present
  - name: Install neovim
    apt:
      update_cache: yes
      pkg:
      - neovim
      - python3-dev
      - python3-pip
      - python3-pynvim
      state: latest
  when: nvim_installed.stdout == ""

