# https://github.com/do-community/ansible-playbooks/blob/master/setup_ubuntu1804/playbook.yml
- name: Install Prerequisites
  apt:
    name: aptitude
    update_cache: yes
    state: latest
    force_apt_get: yes

# Install a newer version of git than ubuntu 20.4's 2.25
- name: Add git stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa

- name: Update apt
  apt:
    update_cache: yes

- name: Install required system packages
  apt:
    name: "{{ sys_packages }}"
    state: latest

