# https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04#option-2-installing-node-js-with-apt-using-a-nodesource-ppa
- name: Install nodesource PPA
  shell: |
    curl -sL https://deb.nodesource.com/setup_16.x | bash

- name: Install node
  apt:
    update_cache: yes
    pkg:
    - nodejs

- name: Install some useful npm packages
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - yarn # apt-get install yarn installs a very old version
    - http-server
    - create-react-app
