- hosts: all
  become: false
  remote_user: "{{ create_user }}"
  vars_files:
    - vars/default.yml

  tasks:
    - import_tasks: gh-configure.yml
    - import_tasks: github-hosts-key.yml
    - import_tasks: neovim-configure.yml
    - import_tasks: dotfiles.yml
    - import_tasks: bin-scripts.yml
    - import_tasks: doctl-configure.yml
