- name: Check whether terraform is already installed
  shell: which terraform
  ignore_errors: yes
  register: terraform_installed

- block:
  - set_fact: homedir="/home/{{ create_user }}"

  - name: Create cache directory
    file:
      path: "{{ homedir }}/.terraform_cache"
      state: directory
      mode: '0755'

  - name: Download and unpack terraform
    ansible.builtin.unarchive:
      src: https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
      dest: /usr/local/bin
      mode: 0755
      remote_src: yes

  when: terraform_installed.stdout == ""
